# Generated by Django 5.0.2 on 2024-03-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkout_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('compname', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('pincode', models.CharField(max_length=6)),
                ('mobile', models.CharField(max_length=10)),
                ('emails', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RenameModel(
            old_name='contact_details',
            new_name='contact_detail',
        ),
    ]
